# Generated by Django 3.1.4 on 2020-12-08 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201207_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.organization'),
        ),
    ]
