# Generated by Django 3.1.4 on 2020-12-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
