# Generated by Django 3.1.4 on 2020-12-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201206_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblistingskill',
            name='job_listing',
        ),
        migrations.RemoveField(
            model_name='joblistingskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobofferskill',
            name='joboffer',
        ),
        migrations.RemoveField(
            model_name='jobofferskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Joblisting',
        ),
        migrations.DeleteModel(
            name='JobListingSkill',
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
        migrations.DeleteModel(
            name='JobOfferSkill',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
